model_config:
  unit:
    base_args:
      num_queries:
        # entry to detect the heads needed
        vl:
          hateful_memes: 25
      share_decoders: true
      decoder_hidden_dim: 768
      dilation: true
      use_task_embedding_in_img_encoder: false
      use_task_embedding_in_lang_encoder: false
    losses:
    - logit_bce
    # initialize the ResNet convnet backbone from DETR
    base_ckpt_path: https://dl.fbaipublicfiles.com/detr/detr-r50-dc5-f0fb7ef5.pth
    base_ckpt_load_backbone_only: true

evaluation:
  metrics:
  - type: accuracy
    key: accuracy
    datasets:
    - visual_entailment
    - glue_qnli
    - glue_qqp
    - glue_sst2
    - glue_mnli_mismatched
    - hateful_memes

optimizer:
  type: adam_w  # HuggingFace transformer's AdamW
  params:
    lr: 5e-5
    eps: 1e-8
    weight_decay: 1e-4

scheduler:
  type: warmup_cosine
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

training:
  num_workers: 2
  # these are mostly the same as in COCO detection training
  clip_norm_mode: all
  clip_gradients: true
  max_grad_l2_norm: 0.1
  lr_scheduler: true
  lr_ratio: 0.1
  batch_size: 64
  max_updates: 5000
  checkpoint_interval: 500
  evaluation_interval: 500
  dataset_size_proportional_sampling: false
  early_stop:
    enabled: false
    criteria: hatefule_memes/accuracy
    minimize: false
  stdout_capture: false
  find_unused_parameters: true

multitasking:
  enabled: true
  type: ratios
  params:
    sampling_ratios:
      hateful_memes: 1.0

checkpoint:
  max_to_keep: 5
